/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JLabel;

/**
 *
 * @author Mi5
 */
public class InfoPanel extends javax.swing.JPanel {
    
    // <editor-fold defaultstate="collapsed" desc="Getters Code">  
    
    public JLabel getTemperatureLbl(){
        return lblTemperature;
    }
    
    public JLabel getHumidityLbl(){
        return lblHumidity;
    }
    
    public JLabel getPowerLbl(){
        return lblPower;
    }
    
    public JLabel getConnectionLbl(){
        return lblConnection;
    }
    
    public JLabel getAlertLbl(){
        return lblAlert;
    }
    
    // </editor-fold> 
    
    /**
     * Creates new form InfoPanel
     */
    public InfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PropPanel = new javax.swing.JPanel();
        lblTemperature = new javax.swing.JLabel();
        lblHumidity = new javax.swing.JLabel();
        lblPower = new javax.swing.JLabel();
        lblAlert = new javax.swing.JLabel();
        lblConnection = new javax.swing.JLabel();

        PropPanel.setBackground(new java.awt.Color(239, 246, 238));

        lblTemperature.setBackground(new java.awt.Color(51, 51, 51));
        lblTemperature.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblTemperature.setForeground(new java.awt.Color(51, 51, 51));
        lblTemperature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/thermometer.png"))); // NOI18N
        lblTemperature.setText("Temperature");

        lblHumidity.setBackground(new java.awt.Color(51, 51, 51));
        lblHumidity.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblHumidity.setForeground(new java.awt.Color(51, 51, 51));
        lblHumidity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/three-drops.png"))); // NOI18N
        lblHumidity.setText("Humidity");

        lblPower.setBackground(new java.awt.Color(51, 51, 51));
        lblPower.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblPower.setForeground(new java.awt.Color(51, 51, 51));
        lblPower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power.png"))); // NOI18N
        lblPower.setText("Power Consumption");

        lblAlert.setBackground(new java.awt.Color(51, 51, 51));
        lblAlert.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblAlert.setForeground(new java.awt.Color(51, 51, 51));
        lblAlert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shield.png"))); // NOI18N
        lblAlert.setText("Alert");

        lblConnection.setBackground(new java.awt.Color(51, 51, 51));
        lblConnection.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblConnection.setForeground(new java.awt.Color(51, 51, 51));
        lblConnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/connection.png"))); // NOI18N
        lblConnection.setText("Connection");

        javax.swing.GroupLayout PropPanelLayout = new javax.swing.GroupLayout(PropPanel);
        PropPanel.setLayout(PropPanelLayout);
        PropPanelLayout.setHorizontalGroup(
            PropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConnection)
                    .addComponent(lblAlert)
                    .addComponent(lblPower)
                    .addComponent(lblHumidity)
                    .addComponent(lblTemperature))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PropPanelLayout.setVerticalGroup(
            PropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTemperature)
                .addGap(18, 18, 18)
                .addComponent(lblHumidity)
                .addGap(18, 18, 18)
                .addComponent(lblPower)
                .addGap(18, 18, 18)
                .addComponent(lblConnection)
                .addGap(18, 18, 18)
                .addComponent(lblAlert)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PropPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PropPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PropPanel;
    private javax.swing.JLabel lblAlert;
    private javax.swing.JLabel lblConnection;
    private javax.swing.JLabel lblHumidity;
    private javax.swing.JLabel lblPower;
    private javax.swing.JLabel lblTemperature;
    // End of variables declaration//GEN-END:variables
}
